import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F45100",
  },
  content: {
    flex: 1,
    backgroundColor: "#F3F4F6",
    padding: 18,
  },
  topRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#0E2240",
    flex: 1,
  },
  addButton: {
    backgroundColor: "#F45100",
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  addButtonText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 14,
  },
  errorBanner: {
    backgroundColor: "#FDE2E2",
    color: "#B42318",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginTop: 14,
  },
  centerState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingBottom: 80,
  },
  loadingText: {
    marginTop: 10,
    color: "#7A8394",
  },
  listContent: {
    paddingTop: 18,
    paddingBottom: 24,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  cardTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: "#0E2240",
    marginBottom: 4,
  },
  cardMeta: {
    color: "#667085",
    marginBottom: 2,
  },
  cardPrice: {
    color: "#F45100",
    fontWeight: "800",
    marginTop: 8,
  },
  imagePickerButton: {
    borderWidth: 1,
    borderColor: "#D0D5DD",
    borderStyle: "dashed",
    borderRadius: 16,
    backgroundColor: "#fff",
    paddingVertical: 18,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  imagePickerButtonActive: {
    borderColor: "#F45100",
    backgroundColor: "#FFF7ED",
  },
  imagePickerIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#FFE2D1",
    alignItems: "center",
    justifyContent: "center",
  },
  imagePickerTitle: {
    color: "#0E2240",
    fontWeight: "800",
    fontSize: 15,
  },
  imagePickerSubtitle: {
    color: "#667085",
    textAlign: "center",
    lineHeight: 20,
  },
  imagePreviewCard: {
    marginTop: 12,
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: "#E5E7EB",
  },
  imagePreview: {
    width: "100%",
    height: 180,
  },
  imagePreviewFooter: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: "#fff",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  imagePreviewText: {
    color: "#475467",
    flex: 1,
  },
  imagePreviewAction: {
    color: "#F45100",
    fontWeight: "800",
  },
  modalSafeArea: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  modalHeader: {
    paddingHorizontal: 18,
    paddingVertical: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
    backgroundColor: "#fff",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#0E2240",
  },
  formContent: {
    padding: 18,
    paddingBottom: 40,
  },
  formHint: {
    color: "#667085",
    marginBottom: 16,
  },
  label: {
    fontSize: 14,
    fontWeight: "700",
    color: "#0E2240",
    marginBottom: 8,
    marginTop: 10,
  },
  input: {
    borderWidth: 1,
    borderColor: "#D0D5DD",
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: "#101828",
  },
  textArea: {
    minHeight: 100,
    textAlignVertical: "top",
  },
  selector: {
    borderWidth: 1,
    borderColor: "#D0D5DD",
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  selectorText: {
    color: "#101828",
    flex: 1,
  },
  selectorPlaceholder: {
    color: "#98A2B3",
  },
  selectorOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "center",
    padding: 24,
  },
  selectorModal: {
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 18,
    maxHeight: "70%",
  },
  selectorTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#0E2240",
    marginBottom: 12,
  },
  selectorOption: {
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#EAECF0",
  },
  selectorOptionText: {
    color: "#101828",
  },
  selectorClose: {
    marginTop: 14,
    backgroundColor: "#F45100",
    borderRadius: 12,
    alignItems: "center",
    paddingVertical: 12,
  },
  selectorCloseText: {
    color: "#fff",
    fontWeight: "700",
  },
  unitRow: {
    flexDirection: "row",
    gap: 10,
  },
  unitButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#D0D5DD",
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
    backgroundColor: "#fff",
  },
  unitButtonActive: {
    borderColor: "#F45100",
    backgroundColor: "#FFF1EB",
  },
  unitButtonText: {
    color: "#475467",
    fontWeight: "700",
  },
  unitButtonTextActive: {
    color: "#F45100",
  },
  switchRow: {
    marginTop: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  scheduleTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#0E2240",
    marginTop: 20,
  },
  scheduleHint: {
    color: "#667085",
    marginTop: 6,
    marginBottom: 10,
  },
  scheduleCard: {
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 14,
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#EAECF0",
  },
  scheduleHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  scheduleDay: {
    fontWeight: "700",
    color: "#101828",
  },
  scheduleInputsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 12,
  },
  timeInput: {
    flex: 1,
  },
  formError: {
    marginTop: 14,
    color: "#B42318",
    fontWeight: "600",
  },
  submitButton: {
    marginTop: 20,
    backgroundColor: "#F45100",
    borderRadius: 14,
    alignItems: "center",
    paddingVertical: 16,
  },
  submitButtonDisabled: {
    opacity: 0.7,
  },
  submitButtonText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 15,
  },
});

export default styles;
